CREATE TABLE games
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status     VARCHAR(255),
    state_json OID,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_games PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    wins     INTEGER                                 NOT NULL,
    loses    INTEGER                                 NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_username UNIQUE (username);