CREATE TABLE chat
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    game_id    BIGINT                                  NOT NULL,
    message    VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_chat PRIMARY KEY (id)
);

ALTER TABLE chat
    ADD CONSTRAINT FK_CHAT_ON_GAME FOREIGN KEY (game_id) REFERENCES games (id);

ALTER TABLE chat
    ADD CONSTRAINT FK_CHAT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);